bpmn-io/properties-panel

src/bpmn-properties-panel/entries/ReferenceSelect.js
src/bpmn-properties-panel/provider/bpmn/BpmnPropertiesProvider.js
src/bpmn-properties-panel/provider/bpmn/properties/ErrorProps.js
src/bpmn-properties-panel/provider/bpmn/properties/MessageProps.js
src/bpmn-properties-panel/provider/bpmn/properties/index.js
src/bpmn-properties-panel/provider/bpmn/utils/ElementUtil.js
src/bpmn-properties-panel/provider/bpmn/utils/EventDefinitionUtil.js
src/properties-panel/components/entries/Select.js
test/spec/bpmn-properties-panel/provider/bpmn/BpmnPropertiesProvider.bpmn
test/spec/bpmn-properties-panel/provider/bpmn/BpmnPropertiesProvider.spec.js
test/spec/bpmn-properties-panel/provider/bpmn/ErrorProps.bpmn
test/spec/bpmn-properties-panel/provider/bpmn/ErrorProps.spec.js
test/spec/bpmn-properties-panel/provider/bpmn/MessageProps.bpmn
test/spec/bpmn-properties-panel/provider/bpmn/MessageProps.spec.js
test/spec/bpmn-properties-panel/provider/bpmn/ReferenceSelect.spec.js

Closes #38 
This adds basic support for
* BPMN Errors
* BPMN Messages
Some notes to the reviewer:
* The zeebe specific message properties will be added on top in another PR (cf. #50). 
* The border below the two action options of the selects won't be implemented by now
* For now we have two `ElementUtil` which a bit of code duplication. Rationale: We don't know where the ZeebePropertiesProvider will live in the future. That's why I wanted to minimize the shared code for the providers.

BPMN Errors + Messages

---

src/bpmn-properties-panel/provider/zeebe/properties/OutputPropagationProps.js
src/bpmn-properties-panel/provider/zeebe/properties/TargetProps.js

Using absolute paths inside the library will break rollup, e.g. when using it for our user testing prototype.

fix(zeebe-provider): avoid absolute paths in library code

---

src/bpmn-properties-panel/BpmnPropertiesPanel.js
test/spec/bpmn-properties-panel/BpmnPropertiesPanel.spec.js
test/spec/bpmn-properties-panel/mocks/index.js

This prevents that we react to element updates for deleted elements. This is necessary because there might `element.changed` updates when an element got removed.
Closes #20

fix(bpmn-properties-panel): do not select deleted elements

---

assets/properties-panel.css

Until we don't have proper data markers, we discussed making the "dirty / configured" - state less prominent.
**before**
**after**

style: remove bold title headers

---

assets/properties-panel.css
src/bpmn-properties-panel/provider/bpmn/BpmnPropertiesProvider.js
src/bpmn-properties-panel/provider/bpmn/properties/DocumentationProps.js
src/bpmn-properties-panel/provider/bpmn/properties/ErrorProps.js
src/bpmn-properties-panel/provider/bpmn/properties/MessageProps.js
src/bpmn-properties-panel/provider/bpmn/properties/ProcessProps.js
src/bpmn-properties-panel/provider/zeebe/properties/ConditionProps.js
src/bpmn-properties-panel/provider/zeebe/properties/FormProps.js
src/bpmn-properties-panel/provider/zeebe/properties/MessageProps.js
src/bpmn-properties-panel/provider/zeebe/properties/MultiInstanceProps.js
src/bpmn-properties-panel/provider/zeebe/properties/OutputPropagationProps.js
src/bpmn-properties-panel/provider/zeebe/properties/TargetProps.js
src/bpmn-properties-panel/provider/zeebe/properties/TaskDefinitionProps.js
src/properties-panel/PropertiesPanel.js
src/properties-panel/components/Group.js
src/properties-panel/components/ListGroup.js
src/properties-panel/components/entries/Checkbox.js
src/properties-panel/components/entries/Select.js
src/properties-panel/components/entries/TextArea.js
src/properties-panel/components/entries/TextField.js
src/properties-panel/components/entries/ToggleSwitch.js
test/spec/properties-panel/components/Checkbox.spec.js
test/spec/properties-panel/components/Group.spec.js
test/spec/properties-panel/components/ListGroup.spec.js
test/spec/properties-panel/components/Select.spec.js
test/spec/properties-panel/components/TextArea.spec.js
test/spec/properties-panel/components/TextField.spec.js
test/spec/properties-panel/components/ToggleSwitch.spec.js

Closes #23 
* moves list count markers to the right
* introduces data markers for normal groups - general approach: a group is `edited` when at least one entry is `edited`
* improves title attributes with data markers for header titles as a quick fix ==> Note: we will handle the whole `title` story on the general design polishing!

Data Markers

---

src/properties-panel/PropertiesPanel.js

Not fixing any bug, but it's generally good advice to assign unique keys to child components.

chore(properties-panel): assign key per group component

---

assets/properties-panel.css
src/bpmn-properties-panel/provider/bpmn/properties/Id.js
src/bpmn-properties-panel/provider/bpmn/properties/ProcessProps.js
src/bpmn-properties-panel/provider/bpmn/utils/ValidationUtil.js
src/properties-panel/components/entries/TextField.js
test/spec/bpmn-properties-panel/provider/bpmn/Id.bpmn
test/spec/bpmn-properties-panel/provider/bpmn/Id.spec.js
test/spec/bpmn-properties-panel/provider/bpmn/ProcessProps.spec.js
test/spec/properties-panel/components/TextField.spec.js

Closes #27 
* adds validation for ids
* adds basic validation styling (cf. [styles from Zeplin](https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327/screen/60d9619fbeb59812106abf00))
Note: I was thinking about adding validation as a general concern for each entry type, but since we currently only validate this particular property and will add [linting as the general validation feature](https://github.com/camunda/camunda-modeler-design/issues/14), I decided to keep it simple and only support it for text fields for now. We can easily add validation for more entry types later.

ID Validation

---

src/PropertiesPanel.js
src/components/ListGroup.js
src/components/entries/Collapsible.js
test/spec/components/Collapsible.spec.js
test/spec/components/ListGroup.spec.js

This makes it possible to have lists non-editable, which includes
* no adding of items
* no removal of items
* disable default alphanumeric sorting
Required by https://github.com/bpmn-io/bpmn-properties-panel/issues/25

Non editable list groups

---

package.json
src/PropertiesPanel.js
src/components/ListGroup.js
test/spec/components/ListGroup.spec.js

Only handle the sorting/ordering effects when the selected element itself did not change. This fixes some buggy behaviors that, e.g.
* the autoFocus behavior kicks in place when switching elements (cf. #63)
* items state gets (wrongly) persisted between element switches (cf. #86, part 1)
It is not fixing: https://github.com/bpmn-io/properties-panel/issues/90 (follow up)
Closes #63
Closes #86
Required by https://github.com/bpmn-io/bpmn-properties-panel/pull/63

fix(list-group): only execute order effects when element did not change

---

assets/properties-panel.css

Makes sure collapsible entry headers have default cursor and can't be selected. Before:

fix(css): default cursor when hovering collapsible entry header

---

assets/properties-panel.css
src/components/entries/Simple.js
test/spec/components/Simple.spec.js

Adds a simple text component (without labels, descriptions, ...)
Required by https://github.com/bpmn-io/bpmn-properties-panel/pull/100 (Inputs & Outputs Lists)

Simple text component

---

assets/properties-panel.css

Related to https://github.com/bpmn-io/bpmn-properties-panel/issues/21
Related to https://github.com/bpmn-io/bpmn-properties-panel/issues/115
----
This unbuilds the custom Checkbox component which was in a WIP state and not meant to be included in the final design (cf. https://github.com/bpmn-io/bpmn-properties-panel/issues/90). We should keep the form components as default as possible and let the using components (Camunda Modeler, ...) decide how they look like.
This also fixes known issues for the Checkbox as https://github.com/bpmn-io/bpmn-properties-panel/issues/21 + https://github.com/bpmn-io/bpmn-properties-panel/issues/115.

style: unbuild custom checkbox component

---

src/components/ListItem.js
src/components/entries/List.js
test/spec/components/List.spec.js
test/spec/components/ListItem.spec.js

`<select>` elements can now be auto-focused.
---
Closes #100

fix(list-item): auto-focus works for <select> elements

---

src/components/entries/List.js
test/spec/components/List.spec.js

* Related to bpmn-io/properties-panel#96

feat(List): insert to bottom given no compareFn

---

assets/properties-panel.css

Styles disabled inputs according to https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v15/.
Example:
_Throw expression_ input is disabled.

style: add disabled input styles

---

assets/properties-panel.css
src/components/DropdownButton.js
src/components/HeaderButton.js
test/spec/components/DropdownButton.spec.js
test/spec/components/HeaderButton.spec.js

This PR:
* removes default button font size which is not used anywhere (https://github.com/bpmn-io/properties-panel/commit/01adb3a25e929aca933c0d7462cb8017a4ccc459)
* adds and exposes HeaderButton
* adds and exposes DropdownButton
The components will be used in the Element Templates Group.
Related to https://github.com/bpmn-io/bpmn-properties-panel/issues/149
Test via https://github.com/bpmn-io/bpmn-properties-panel/tree/149-add-dropdown-button and `npm run start:templates`.

Add dropdown button

---

assets/properties-panel.css

Added missing description styles (cf. [prototype v16](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v16/) (Task "Custom form elements" > Section "Custom form: input"))
Related to https://github.com/bpmn-io/bpmn-properties-panel/issues/202
-----
Command to try that out
```sh
npx @bpmn-io/sr bpmn-io/bpmn-properties-panel -c "npm run start:cloud" -l "bpmn-io/properties-panel#202-description-styles"
```

style: add missing description styles

---

.github/workflows/CI.yml
rollup.config.js

Closes #127.
This also includes changes to the CI config, now triggering builds on windows, mac and linux platforms.

fix: rollup now sets up correct paths for preact on windows builds

---

karma.config.js
package-lock.json
package.json
src/components/entries/Simple.js
test/TestHelper.js
test/spec/components/Checkbox.spec.js
test/spec/components/Collapsible.spec.js
test/spec/components/DropdownButton.spec.js
test/spec/components/Group.spec.js
test/spec/components/Header.spec.js
test/spec/components/HeaderButton.spec.js
test/spec/components/List.spec.js
test/spec/components/ListGroup.spec.js
test/spec/components/ListItem.spec.js
test/spec/components/NumberField.spec.js
test/spec/components/Select.spec.js
test/spec/components/Simple.spec.js
test/spec/components/TextArea.spec.js
test/spec/components/TextField.spec.js
test/spec/components/ToggleSwitch.spec.js

This
* adds basic a11y testing infrastructure via `axe-core`
* defines basic rules set we testing against 
* `best-practice`
* `wcag2a`
* `wcag2aa`,
* `cat.semantics` (some additional rules to ensure we use semantic HTML, something we focus on in the past)
* adds unit tests for all components 
* fixes a minor a11y issue with the `Simple` component (no label)

Add basic accessibility tests

---

src/PropertiesPanel.js
src/components/Group.js
src/components/ListGroup.js
src/components/ListItem.js
src/components/entries/Collapsible.js
src/components/entries/List.js
test/spec/PropertiesPanel.spec.js
test/spec/components/Collapsible.spec.js
test/spec/components/Group.spec.js
test/spec/components/List.spec.js
test/spec/components/ListItem.spec.js

* all group and entry components specified as `component` are actual components, not elements
* props can be passed from parent to child components
* props specified when creating group or entry will be passed to component
---
Required by https://github.com/bpmn-io/bpmn-js-properties-panel/pull/590

feat: render components instead of elements

---

CHANGELOG.md

Preparation for the release of v0.11.0 which is required by https://github.com/bpmn-io/bpmn-js-properties-panel/pull/590.

chore(CHANGELOG): update to v0.11.0

---

package-lock.json
package.json
src/PropertiesPanel.js
src/components/Group.js
src/components/ListGroup.js
src/components/entries/Checkbox.js
src/components/entries/Collapsible.js
src/components/entries/Select.js
src/components/entries/TextField.js
src/context/EventContext.js
src/context/PropertiesPanelContext.js
src/context/index.js
src/hooks/index.js
src/hooks/useEvent.js
src/hooks/useEventBuffer.js
src/hooks/usePrevious.js
src/hooks/useShowEntryEvent.js
src/hooks/useShowErrorEvent.js
test/spec/components/Checkbox.spec.js
test/spec/components/Collapsible.spec.js
test/spec/components/Group.spec.js
test/spec/components/ListGroup.spec.js
test/spec/components/Select.spec.js
test/spec/components/TextField.spec.js
test/spec/hooks/useEvent.spec.js
test/spec/hooks/useEventBuffer.spec.js
test/spec/hooks/useShowEntryEvent.spec.js
test/spec/hooks/useShowErrorEvent.spec.js

`EventContext` is introduced. Through this context, one can subscribe to events using the `useEvent` hook.
```js
function Foo() {
useEvent('foo', (event) => console.log(event));
// ...
}
```
The `useEventBuffer` hook is introduced to buffer events that will be re-fired during the passive effect phase. If a component is rendered after an event was fired it will still catch the event.
```js
function Foo() {
useEvent('foo', (event) => console.log(event));
// ...
}
function Bar() {
useEventBuffer([ 'foo' ], eventBus);
return <Foo />;
}
```
It allows the user to do
```js
selection.select(element);
eventBus.fire('propertiesPanel.showEntry', { ... });
```
without using `setTimeout` or similar workarounds.
The `useShowEntryEvent` hook is introduced to make subscribing to …

Be Able to Show Entry and Error through Event

---

src/PropertiesPanel.js
src/components/Group.js
src/context/LayoutContext.js
test/spec/components/Group.spec.js

related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/618
for integration PR in bpmn-js properties panel, see https://github.com/bpmn-io/bpmn-js-properties-panel/pull/621

feat(group): make inital open state configurable

---

src/components/entries/Checkbox.js
src/components/entries/Select.js
src/components/entries/TextField.js
src/context/EventContext.js
src/hooks/useShowEntryEvent.js
src/hooks/useShowErrorEvent.js
test/spec/components/Checkbox.spec.js
test/spec/components/Select.spec.js
test/spec/components/TextField.spec.js
test/spec/hooks/useShowErrorEvent.spec.js

This PR contains a couple of small adjustments to the recently added feature of showing entries and errors:
* rename `error` property of `propertiesPanel.showError` event to `message`
* unset temporary error on `propertiesPanel.updated`
* do not set focus if already set
---
Required by https://github.com/bpmn-io/bpmn-js-properties-panel/pull/601

Show Entry and Error Adjustments

---

src/PropertiesPanel.js
src/context/EventContext.js
src/hooks/useEvent.js
src/hooks/useShowErrorEvent.js
test/spec/hooks/useEvent.spec.js
test/spec/hooks/useShowEntryEvent.spec.js
test/spec/hooks/useShowErrorEvent.spec.js

Make the properties panel fly without an event bus. 🛫

fix: make event bus prop optional

---

assets/properties-panel.css

Related to https://github.com/camunda/camunda-modeler/issues/2831.
The negative margin is there to 'hide' the last group's separator when a scrollbar is visible.
This avoids that:
This has the side effect of moving the scrollbar itself down a little. Not really visible, and definitely a little weird but I've tried multiple other css tricks without success.
How it will look:
Worth testing on non windows platforms if the scrollbars look different.

fix: remove unnecessary properties panel padding

---

assets/properties-panel.css
src/PropertiesPanel.js
src/components/Header.js
src/components/Placeholder.js
src/components/index.js
src/hooks/useDescriptionContext.js
test/spec/PropertiesPanel.spec.js
test/spec/components/Placeholder.spec.js
test/spec/mocks/index.js

Closes #69 
* Improve placeholder to provide multiple and empty states
* Allows integrators (e.g. bpmn-js-properties-panel) to provide contents 
Note (/cc @andreasgeier): I used `--color-grey-225-10-35` for the text color as the color [in the prototype ](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v18/) offers too less contrast (`--color-grey-225-10-55`). It even broke the built-in a11y integration test (which is a good sign our tests work 👍 )
Example
```sh
npx @bpmn-io/sr "bpmn-io/bpmn-js-properties-panel#use-updated-placeholder" -l "bpmn-io/properties-panel#69-multi-and-empty-state" -c "npm run start:cloud" 
```
**Multiple state**
**Empty state**
Only in theory, not possible via UI.

Enable generic multiple and empty state

---

assets/properties-panel.css
src/components/Group.js
src/components/ListGroup.js
src/hooks/index.js
src/hooks/useStickyIntersectionObserver.js
test/spec/hooks/useStickyIntersectionObserver.spec.js

closes camunda/camunda-modeler-design#118
:warning: Please notice this does not yet include the `Scroll to focus on new added list item` => I will tackle this seperately as a follow-up.
Try this out yourself with:
```
npx @bpmn-io/sr "bpmn-io/bpmn-js-properties-panel" -l "bpmn-io/properties-panel#sticky-headers"  
```

Sticky headers

---

src/components/entries/List.js
test/spec/components/List.spec.js

This is a (late) follow-up of https://github.com/bpmn-io/properties-panel/pull/134 where we allowed props to be passed to the to-be-rendered entry component. This wasn't possible for `List` entries (maybe it was forgotten).
This might be important while implementing https://github.com/bpmn-io/form-js/issues/256 /cc @Skaiir.

feat: pass props to list entry component

---

CHANGELOG.md

* `FEAT`: set errors through context ([#160](https://github.com/bpmn-io/properties-panel/pull/160))
* `FEAT`: useShowEntryEvent hook uses ID ([#160](https://github.com/bpmn-io/properties-panel/pull/160))
* `FEAT`: useEvent hook subscribes immediately ([#160](https://github.com/bpmn-io/properties-panel/pull/160))
* `FEAT`: add focus and error to text area ([#160](https://github.com/bpmn-io/properties-panel/pull/160))

chore(CHANGELOG): update to v0.16.0

---

src/components/entries/TextArea.js
test/spec/components/Select.spec.js
test/spec/components/TextArea.spec.js
test/spec/components/TextField.spec.js

When a text area has an error the styling indicates it (same as text field).
Closes #165

fix: add error class to text area with error

---

assets/properties-panel.css
package-lock.json
package.json
src/components/entries/FEEL/Feel.js
src/components/entries/FEEL/FeelEditor.js
test/spec/components/DropdownButton.spec.js
test/spec/components/Feel.spec.js
test/spec/components/FeelEditor.spec.js
test/spec/components/Group.spec.js
test/spec/components/Placeholder.spec.js

Adds the ability to pass variables to the FEEL editor. Start typing or use ctrl+space to get suggestions.
Try it out using 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel#feel-editor-variables
```

feat: pass variables to FEEL editor

---

assets/properties-panel.css
src/hooks/useStickyIntersectionObserver.js
test/spec/hooks/useStickyIntersectionObserver.spec.js

Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/726
Removes the sticky headers feature until we find a proper fix for https://github.com/bpmn-io/bpmn-js-properties-panel/issues/726.
```sh
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#726-opt-out-sticky-headers
```

chore: remove sticky headers

---

assets/properties-panel.css
src/hooks/useStickyIntersectionObserver.js
test/spec/hooks/useStickyIntersectionObserver.spec.js

related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/726
(see issue for why this was broken)

fix(hooks): set sticky correctly on element change

---

src/components/entries/Checkbox.js
src/components/entries/FEEL/Feel.js
src/components/entries/NumberField.js
src/components/entries/Select.js
src/components/entries/Simple.js
src/components/entries/TextArea.js
src/components/entries/TextField.js
test/spec/components/Checkbox.spec.js
test/spec/components/Feel.spec.js
test/spec/components/NumberField.spec.js
test/spec/components/Select.spec.js
test/spec/components/Simple.spec.js
test/spec/components/TextArea.spec.js
test/spec/components/TextField.spec.js

related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/712
test it out using 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#use-element-as-key
```

chore: use element as key for entries

---

CHANGELOG.md

Even though sticky headers is a fix, they were disabled in 0.18.0, so we should consider it a feature and we cut a minor release

chore(CHANGELOG): update to v0.19.0

---

src/components/entries/FEEL/FeelEditor.js
test/spec/components/FeelEditor.spec.js

related to https://github.com/camunda/camunda-modeler/issues/3072

fix(FeelEditor): focus editor on container click

---

assets/properties-panel.css
src/components/entries/FEEL/Feel.js
src/components/entries/FEEL/FeelEditor.js
test/spec/components/Feel.spec.js

try it out using 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#feel-editor-syntax-error
```
requires https://github.com/bpmn-io/feel-editor/pull/10

fix(FEEL): show syntax errors

---

src/components/entries/FEEL/Feel.js
test/spec/components/Feel.spec.js

closes #183
test it out: 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#183-feel-required-cut-off -c "npm run start:cloud-templates"
```

fix: keep first character of feel-required expression

---

CHANGELOG.md

I believe that this should be a breaking release even though the refiring of events was an internal the user wasn't necessarily aware of. 
* `CHORE`: do not refire events during effect phase ([#186](https://github.com/bpmn-io/properties-panel/pull/186))
* events are not refired during effect phase anymore, you might have to use timeouts to ensure the events are being caught

chore(CHANGELOG): update to v0.21.0

---

src/components/entries/Checkbox.js
src/components/entries/FEEL/Feel.js
src/components/entries/NumberField.js
src/components/entries/Select.js
src/components/entries/TextArea.js
src/components/entries/TextField.js
src/components/entries/ToggleSwitch.js

The inner component `TextArea`  spreads the `props.onBlur` and `props.onFocus` functions to the native textarea component:
``` 
<textarea
....
onFocus={ props.onFocus }
onBlur={ props.onBlur }
... />
```
But the outer component `TextAreaEntry` never actually exposes the same props to the consumer.

feat: expose onFocus and onBlur functions on TextAreaEntry

---

src/components/entries/ToggleSwitch.js
test/spec/components/ToggleSwitch.spec.js

Root cause: setting `checked = undefined` does not update the toggle state.
related to https://github.com/camunda/camunda-modeler/issues/3233

fix(ToggleSwitch): disable when value gets undefined

---

src/components/entries/FEEL/Feel.js
src/components/entries/FEEL/FeelEditor.js

integration of https://github.com/bpmn-io/feel-editor/pull/32

Restrict feel tooltip placement

---

src/components/entries/FEEL/Feel.js
src/components/entries/TextArea.js
test/spec/components/Feel.spec.js
test/spec/components/TextArea.spec.js

Reported to break focus, cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/810.
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/810.

chore: disable Grammarly on `<textarea />` elements

---

src/components/entries/Select.js
test/spec/components/Select.spec.js

Explicitly set select value to empty rather than undefined.
Undefined values cause the browser to render the first selection.
---
Related to https://github.com/camunda/camunda-modeler/issues/3327

fix: coherce undefined `<Select />` value to empty string

---

src/components/entries/TextArea.js
test/spec/components/TextArea.spec.js

fix: do not grow autoresized text area on first input

---

src/components/entries/Select.js
test/spec/components/Select.spec.js

This PR adds `optgroup` props to the `Select.js` component.
You will be able to use this by adding  `getGroups` function, which returns an array of objects with `key` and `label` fields in the select component props.
For proper functioning, you should add a `groupKey` field into the option(s) object, which, in its turn, should be equal to `key` field of group object
Example:
```
function ExampleComponent(props) {
const { element } = props
const getGroups = (element) => {
return [
{
key: 'first',
label: 'first test group'
},
{
key: 'second',
label: 'second test group'
}
]
}
const getOptions = (element) => {
return [
{
groupKey: 'first',
label: 'Test option 1',
value: 'test1'
},
{
groupKey: 'first',
label: 'Test option 2',
value: 'test2',
disabled: true
},
{
groupKey: 'second',
label: 'Test …
```

feat: add optgroup option for select

---

assets/properties-panel.css

Related to https://github.com/bpmn-io/form-js/pull/316
This allows using code blocks inside descriptions. 
[Example](https://github.com/bpmn-io/form-js/pull/316)

styles: allow `pre` code blocks

---

src/PropertiesPanel.js
src/hooks/useLayoutState.js
test/spec/PropertiesPanel.spec.js
test/spec/components/Collapsible.spec.js
test/spec/components/Feel.spec.js
test/spec/components/Group.spec.js
test/spec/components/ListGroup.spec.js
test/spec/hooks/useLayoutState.spec.js

- Groups: don't use local state in [`useLayoutState`](https://github.com/bpmn-io/properties-panel/blob/e01dd051aba1b4998bcc6f7a591ad7cdf8fc4cf7/src/hooks/useLayoutState.js#L26). Instead, always use the Context value, so outside changes in the layout are reflected in the Groups.
- PropertiesPanel (root): React to `layoutConfig` changes, e.g. from other tabs. Currently, only the initial value is used.
related to https://github.com/camunda/camunda-modeler/issues/2638

feat: use global layout context as single source of truth

---

src/components/ListGroup.js
test/spec/components/ListGroup.spec.js

Found while working on https://github.com/bpmn-io/bpmn-js-example-data-extension/issues/1, cf. https://camunda.slack.com/archives/GP70M0J6M/p1679407286325119
This ensures that we only open the section when the change originated from the `add` button click:

fix(ListGroup): don't open on external changes

---

package-lock.json

This fixes specifically the json5 cve: https://security.snyk.io/vuln/SNYK-JS-JSON5-3182856

deps: fix audit warnings for production

---

src/PropertiesPanel.js
src/hooks/useLayoutState.js
test/spec/PropertiesPanel.spec.js
test/spec/components/Collapsible.spec.js
test/spec/components/Feel.spec.js
test/spec/components/Group.spec.js
test/spec/components/ListGroup.spec.js
test/spec/hooks/useLayoutState.spec.js

with https://github.com/bpmn-io/properties-panel/pull/225 we introduced changes so the layout reacts to external changes.
With the changes, we introduced another re-render cycle during bootstrapping, causing `layoutChanged` and `descriptionLoaded` to be called twice. 
This PR ensures the callbacks are only called once.

fix(PropertiesPanel): only call callbacks once on first render

---

src/components/entries/TextArea.js
test/spec/components/TextArea.spec.js

Mirrors validation behavior of `TextField`.
Closes https://github.com/bpmn-io/properties-panel/issues/233

feat: support local `TextArea#validate` hook

---

src/PropertiesPanel.js
src/hooks/useStickyIntersectionObserver.js
test/spec/hooks/useStickyIntersectionObserver.spec.js

related to https://github.com/camunda/camunda-modeler/pull/3556

Fix flickering on desktop modeler tab change

---

src/hooks/useStickyIntersectionObserver.js
test/spec/hooks/useStickyIntersectionObserver.spec.js

related to https://github.com/camunda/web-modeler/issues/4650
This PR:
- subscribes to attach/detach events
- then updates the scroll container
- Removes/Adds an Intersection Observer to the new scrollContainer

fix(Groups): update sticky observer on attach/detach

---

src/components/entries/FEEL/Feel.js
src/components/entries/NumberField.js
src/components/entries/index.js
test/spec/components/Feel.spec.js

Related to bpmn-io/form-js#653
Adds an optional FEEL number field entry. This enabled us to create number properties with FEEL support (e.g. `min`, `max`, `minLength`, `maxLength` in form-js, https://github.com/bpmn-io/form-js/pull/668).

feat(feel): add number feel entry

---

CHANGELOG.md
src/components/entries/FEEL/Feel.js
src/components/entries/NumberField.js
src/components/entries/Select.js
src/components/entries/TextArea.js
src/components/entries/TextField.js
src/components/entries/templating/Templating.js
test/spec/components/Feel.spec.js
test/spec/components/NumberField.spec.js
test/spec/components/Select.spec.js
test/spec/components/Templating.spec.js
test/spec/components/TextArea.spec.js
test/spec/components/TextField.spec.js

Whether invalid values are persisted on errors or not should be a concern of the application. This PR introduces that we also propagate invalid values to the app.
Integrates into bpmn-js-properties-panel: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/938
related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/928
related to https://github.com/camunda/camunda-modeler/issues/3357

feat: propagate invalid values to `setValue`

---

test/spec/components/Feel.spec.js
test/spec/components/NumberField.spec.js
test/spec/components/Select.spec.js
test/spec/components/Templating.spec.js
test/spec/components/TextArea.spec.js
test/spec/components/TextField.spec.js

We don't want to test the validation itself. We want to test what happens given a validation error is returned or not.
---
Follow-up to https://github.com/bpmn-io/properties-panel/pull/252#discussion_r1252805799.

test: simplify validation tests

---

assets/properties-panel.css
src/components/Group.js
src/components/ListGroup.js
src/hooks/index.js
src/hooks/useError.js
test/spec/components/Group.spec.js
test/spec/components/ListGroup.spec.js

closes #180
Unfortunately, `@bpmn-io/sr` does not work for this one. To test it out, link the properties-panel from `@camunda/linting` and change the import path for the properties-panel css to `@bpmn-io/properties-panel`: https://github.com/camunda/linting/blob/549ec9cfbed996845312015a804090ba08aeffb6/test/spec/modeler/Linting.spec.js#L40

feat: add error markers to groups

---

assets/properties-panel.css
src/components/entries/Checkbox.js
src/components/entries/FEEL/Feel.js
src/components/entries/Select.js
src/components/entries/TextArea.js
src/components/entries/TextField.js
src/components/entries/ToggleSwitch.js
src/components/entries/Tooltip.js
test/spec/components/Tooltip.spec.js

Closes #202
* Adds tooltip components
* Adds it to input fields: Checkbox, Feel, Textfield, TextArea, ToggleSwitch
Can be tested against https://github.com/bpmn-io/bpmn-js-properties-panel/tree/tooltips

Support tooltips

---

assets/properties-panel.css
src/PropertiesPanel.js
src/components/entries/Checkbox.js
src/components/entries/FEEL/Feel.js
src/components/entries/Select.js
src/components/entries/TextArea.js
src/components/entries/TextField.js
src/components/entries/ToggleSwitch.js
src/components/entries/Tooltip.js
src/context/TooltipContext.js
src/context/index.js
src/hooks/index.js
src/hooks/useTooltipContext.js
test/spec/PropertiesPanel.spec.js
test/spec/components/Tooltip.spec.js
test/spec/hooks/useTooltipContext.spec.js

Closes #261 
Test against [this branch](https://github.com/bpmn-io/bpmn-js-properties-panel/tree/tooltips): Existing [descriptions provided by context](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/contextProvider/zeebe/DescriptionProvider.js) were changed to tooltips provided by context.
_The actual tooltip content and where they appear will be tackled later_

Allow tooltip via context

---

assets/properties-panel.css
src/components/Group.js
src/components/ListGroup.js
src/components/entries/Tooltip.js

Test against [this `bpmn-js-properties-panel` branch](https://github.com/bpmn-io/bpmn-js-properties-panel/tree/tooltips)

Support tooltips in group headers

---

assets/properties-panel.css

This crashes our form-js visual regression tests 🐵 
https://github.com/bpmn-io/form-js/actions/runs/5736564529/job/15546412474?pr=708

style: use correct header styles in popups

---

src/PropertiesPanel.js
src/components/entries/FEEL/FeelPopup.js
test/spec/components/FeelPopup.spec.js

Related to https://github.com/bpmn-io/properties-panel/issues/277
This allows to set the parent container of the FEEL popup via a property. The default keeps `document.body`.
For context: We had problems in the Web Modeler properly cleaning up the popups when navigating outside of the editor (cf. https://camunda.slack.com/archives/C046XS3GGCR/p1693400946971909). For example, in the forms editor, we can set the container to the Form Playground Root.
Cf. to the implementation in form-js as an example of how to use this.
* https://github.com/bpmn-io/form-js/pull/795
* https://github.com/camunda/form-playground/pull/101 ([Demo](https://feel-popup-root--camunda-form-playground.netlify.app/))

feat(feel-popup): allow defining popup container

---

src/components/entries/FEEL/Feel.js
test/spec/components/Feel.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3845

fix(FEEL): reported error switching

---

src/PropertiesPanel.js
src/components/entries/FEEL/FeelPopup.js
src/features/feel-popup/FeelPopupModule.js
src/features/feel-popup/index.js
src/features/index.js
test/spec/components/FeelPopup.spec.js

Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/974
This provides the capability to hook into the feel popup lifecycle as
* `feelPopup.opened`
* `feelPopup.closed`
* `feelPopup._open`
* `feelPopup._close`
* `feelPopup._isOpen`
Furthermore, this adds a feature service that integrators can use to interact with the popup. Cf. to this example [on how to use it](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/975). I didn't add particular test coverage for this module in this project similar to `debounceInput` as I saw we do not have a proper didi-like test setup in the core framework.
```js
const feelPopup = bpmnjs.get('feelPopup');
console.log('is open', feelPopup._isOpen());
feelPopup.close();
feelPopup.open(someElement, { type: 'feel' }, …
```

Feel Popup event support

---

package-lock.json
src/components/Group.js
test/spec/components/Group.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3815
As per https://github.com/camunda/camunda-modeler/issues/3815#issuecomment-1733038161

Fix data marker update

---

CHANGELOG.md
src/components/Popup.js
src/components/entries/FEEL/FeelPopup.js
test/spec/components/FeelPopup.spec.js

Adds new lifecycle events:
- `feelPopup.open` - fired before the popup is mounted
- `feelPopup.opened` - fired after the popup is mounted. Event context contains the DOM node of the popup
- `feelPopup.close` - fired before the popup is unmounted. Event context contains the DOM node of the popup.
- `feelPopup.closed` - fired after the popup is unmounted
---
Context: 
This might be a bit over-engineered. We basically need 2 events to allow us to implement `focusin` and `focusout` as a separate component as described in #290. These are:
- `opened`, fired after mounting the DOM element
- `close`, fired before unmounting
I also added the corresponding `open` (before mount) and `closed` (after unmount) events for completeness, even if we do not use them. I'm not sure on this one, as it adds a …

feat(FEEL): adjust lifecycle events to match conventions

---

CHANGELOG.md
src/assets/properties-panel.css
src/components/Popup.js
src/components/entries/FEEL/FeelPopup.js
src/components/util/dragger.js
test/spec/components/FeelPopup.spec.js
test/spec/components/Popup.spec.js

Drag trap for popups

---

src/components/entries/FEEL/Feel.js
test/spec/components/Feel.spec.js

related to https://github.com/camunda/camunda-modeler/issues/3913
Root cause: the `Number` Component returns parsed floats, so `0` is a falsy value. We need to consider that in propagation of `empty` values.

fix(FEEL): allow value `0` in FEEL number fields

---

README.md

+ fix outdated "we're not bundling" notice.

docs: simplify hacking the project section

---

package.json

Ensures that loaders properly recognize the `mjs` export produced by this `commonjs` module.

chore: change module extension to `mjs`

---

src/assets/properties-panel.css

It's pretty standard for code blocks to use both `<pre>` and `<code>` html tags together. I have removed the double border which arises when using this setup, while keeping the border when they are used individually.

fix(tooltips): remove pre code double borders

---

CHANGELOG.md
package.json

This causes [unintended side-effects](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/985#issuecomment-1761162479) in module bundling.

Revert `mjs` rename

---

karma.config.js
package-lock.json
package.json

Unneeded as we load SVGs [via babel](https://github.com/bpmn-io/properties-panel/blob/main/.babelrc.json).

chore: drop `react-svg-loader`

---

src/components/entries/NumberField.js
src/components/entries/Simple.js
src/components/entries/TextArea.js
src/components/entries/TextField.js

Closes #313 
Passed event.target instead of event as parameter to the debounce method.
To fix issue https://github.com/bpmn-io/properties-panel/issues/313

pass event.target instead of event to make it also work in the shadow dom 

---

src/assets/properties-panel.css
src/components/entries/FEEL/FeelEditor.js

The scrollbar in the FEEL popup editor was hidden when the text was too long.
https://github.com/bpmn-io/properties-panel/assets/1022916/357374e1-0009-4e01-ab55-7fd2572cc72a
Closes #316

fix: Enable scrolling on FEEL popup editor

---

src/assets/properties-panel.css
src/components/entries/Tooltip.js
src/components/entries/index.js
test/spec/components/Tooltip.spec.js

Related to https://github.com/camunda/improved-canvas/issues/18
Can be tested against https://github.com/camunda/improved-canvas/pull/20

feat: allow tooltip re-usability

---

src/components/Popup.js
src/components/entries/FEEL/Feel.js
src/components/entries/FEEL/FeelPopup.js
test/spec/components/Feel.spec.js
test/spec/components/Popup.spec.js

related to https://github.com/camunda/camunda-bpmn-js/issues/312
This PR fixes 2 issues.
1. Automatically close popup when Property panel gets detached
2. Close Popup when source property is removed

fix(Popup): close popup when properties panel detaches

---

src/assets/properties-panel.css

Related to https://github.com/camunda/camunda-modeler/issues/3895
Since the input is auto-resized, FEEL popup editor can be opened to see it better and the FEEL icon is getting in the way of the resizer, i followed the issues' suggestion and removed it.

feat: remove feel input reziser

---

src/assets/properties-panel.css

This prevents it from being hidden below the fold for long expressions:

fix: attach popup-editor trigger to top

---

src/assets/properties-panel.css

@nikku There was a missing fix on the popup editor button from [this PR](https://github.com/bpmn-io/properties-panel/pull/337), on `form-js` it was still wrong

fix: prevent button from taking entire height

---

CHANGELOG.md
src/PropertiesPanel.js
src/components/ListGroup.js
src/components/entries/List.js
test/spec/components/List.spec.js
test/spec/components/ListGroup.spec.js

This pull request aims to fix #311 . Currently, it is being developed.
Closes #311

Removed sorting from `ListGroup` component

---

CHANGELOG.md
src/components/ListItem.js

This ensures that a newly created (and focused) entry is in view:
Related to #311

feat: scroll focused element into view

---

package-lock.json
package.json
src/components/entries/FEEL/Feel.js
src/components/entries/FEEL/FeelEditor.js
src/components/entries/TextArea.js
src/components/entries/TextField.js
test/spec/components/Feel.spec.js
test/spec/components/FeelEditor.spec.js
test/spec/components/TextArea.spec.js
test/spec/components/TextField.spec.js

This PR implements `placeholder` property in the entries used in the element templates project. We can implement it in other entries (where it makes sense) if we decide to adopt placeholders everywhere.
Related to https://github.com/bpmn-io/bpmn-js-element-templates/issues/92

Support placeholder in text and FEEL text entries

---

src/components/ListGroup.js
src/components/ListItem.js
src/components/entries/Collapsible.js
src/components/util/translateFallback.js
test/spec/components/Collapsible.spec.js
test/spec/components/ListGroup.spec.js

Closes #358 
@barmac Sorry for opening a new pull request. I was signed in with the wrong user and was unable to sign the CLA.

Enhance ListGroup and Collapsible components to support translation and add tests for translation

---

src/components/ListGroup.js
src/hooks/useLayoutState.js
test/spec/components/ListGroup.spec.js

* Previously we would render the list group items delayed, with old (outdated) items to be rendered against new model data ([ref](https://github.com/bpmn-io/properties-panel/commit/d426c3366f4f313f839bad1213f7f81744abf40a#diff-43a698bffc8d59870451eb32cfa4f82563203bcf7df48c6e8e86fbdc3c21c64cL227))
* This caused bugs in downstream dependencies (https://github.com/camunda/camunda-modeler/issues/4382)
This PR puts list group, on stable foundations, without magic :tm: :registered: 
-----
Related to https://github.com/camunda/camunda-modeler/issues/4382

Refactor `ListGroup` open close handling

---

src/components/entries/TextArea.js
test/spec/components/TextArea.spec.js

Closes #314
Text area resizes on every render. If it only resizes on initial render, it will not resize when closing and opening sections on properties panel.
https://github.com/bpmn-io/properties-panel/assets/24656920/4de86866-1a71-40d0-9e4a-8a73915b5c65

fix: text area will auto resize on every render

---

src/components/entries/TextArea.js
src/hooks/index.js
src/hooks/useElementVisible.js
test/spec/components/TextArea.spec.js
test/spec/hooks/useElementVisible.spec.js

Closes #314
Text area with `autoResize` property only resizes on initial render and on input. When it's initially rendered inside of closed group or collapsable, it won't properly resize after opening the container.
https://github.com/user-attachments/assets/47a1a43a-078d-4309-a617-4bcd52b4574e
Watch for change of element's visibility and trigger resize when it becomes visible. Since when toggling the container, the text area's style doesn't change directly, I use `ResizeObserver` to detect change of element's size.
https://github.com/user-attachments/assets/c18f790e-8aa2-44e3-a67c-ae902238661c

fix: text area resizes properly every time it becomes visible

---

src/assets/properties-panel.css

Adds styles for headings in tooltips.
Related to https://github.com/camunda/camunda-modeler/issues/4385

feat: add styles for tooltip headings

---

src/components/entries/TextArea.js

Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/713 
Related to https://github.com/camunda/camunda-modeler/issues/3660
Text area will auto resize by default.

feat: auto resize text areas by default

---

package-lock.json
src/components/entries/FEEL/Feel.js
test/spec/components/Feel.spec.js

This ensures that `first-item` is not indicated as a hard error, but a warning. It also prevents `first-item` matches, along with any non-syntax errors, from showing off as a `Unparseable FEEL expression` syntax error.
Try out via 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#first-item-warning
```
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1078

Integrate `first-item` FEEL validation gracefully, as a warning 

---

src/assets/properties-panel.css

Related to https://github.com/camunda/web-modeler/issues/12976
This change remove the focus outline present inside of the popouts. Note this issue was popping up due to a variable naming conflict with [react-pdf](https://www.npmjs.com/package/react-pdf). I don't think it's an absolute necessity to change the variable, but something to consider. 
See the full RCA [here](https://github.com/camunda/web-modeler/issues/12976#issuecomment-2656485410).
Easiest way I can think: just set `--input-focus-border-color` to something globally somewhere where you can access the popup, put focus within it.

fix: remove the focus border within feel popups

---

src/components/entries/Tooltip.js
test/spec/components/Tooltip.spec.js

I reworked the Tooltip component to rely on the React event handlers instead of hooking into document events and running hundreds of checks for every `mousemove`, `wheel` and `focusout` event.
In the process, I fixed the bug that made the tooltip disappear when you click on it to try to copy something after opening it with a click on the header, not hovering. (cf. https://github.com/camunda/camunda-modeler/pull/4841#issuecomment-2671382075)
The removed test `should not render if trigger element no longer hovered - scroll` doesn't seem to make sense. Scrolling shouldn't hide the tooltip itself, only if it actually moves the cursor out of it. If it does, it fires `mouseleave` event anyway.
Interesting finding: potentially we could rely on …

fix: make tooltip persist when trying to copy from it + refactor

---

src/components/entries/TextArea.js
src/components/entries/TextField.js
test/spec/components/TextArea.spec.js
test/spec/components/TextField.spec.js

Closes #309
Extra whitespaces at the end are trimmed in both text area and text field
You can test this works via 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#trim-whitespaces
```

trim whitespaces when user leaves the field

---

src/components/entries/FEEL/Feel.js
src/components/entries/TextArea.js
src/components/entries/TextField.js

This makes sure we commit the erased value. Unfortunately, I was not able to write tests for this (check related issue) even though we can reproduce failures with bpmn-js-properties-panel test suite.
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1127
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#fix-trimming
```
Related discussion: https://camunda.slack.com/archives/C032H77434N/p1747907690237519

Fix trimming

---

src/components/entries/FEEL/Feel.js
src/components/entries/TextArea.js
src/components/entries/TextField.js

This is supposed to fix the performance issue reported via https://camunda.slack.com/archives/C032H77434N/p1748016281595929
Since we depend on the element only, the debounce callback will not change constantly.
https://github.com/user-attachments/assets/08e70eba-0b6e-4a0c-a66c-06c93c226300

fix: depend on element instead of value

---

test/spec/components/FeelEditor.spec.js

This increases the timeout for a flaky test which on Windows CI is close to the default 2s limit ([example](https://github.com/bpmn-io/properties-panel/actions/runs/15560004123/job/43809676822#step:7:254)). I don't see anything wrong with the test itself, and it consistently passed with the increased timeout.

test: increase timeout for a slow test

---

src/assets/properties-panel.css
src/components/entries/List.js
src/hooks/useStickyIntersectionObserver.js

Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1103
These changes allow list headers to become sticky to the properties panel when scrolled past. This is particularly useful when managing long lists of values, as it eliminates the need to constantly scroll back up to add new elements to a list or map. It is especially convenient for maps where each entry contains multiple fields making scrolling distance quite long.
Additionally, there is the ability to set nesting levels for headers, which is useful when working with multiple nested lists or maps. This value is used to set z-index and top margin for the sticky position and to properly detect stickiness with `useStickyIntersectionObserver` hook.
A value of 1 means that the list is at the first nesting level within …

Sticky list headers

---

src/components/entries/NumberField.js
test/spec/components/NumberField.spec.js
test/spec/components/TextField.spec.js

Make tooltips work with number fields.
Related to https://github.com/camunda/camunda-modeler/issues/5102

fix: allow tooltip on number field

---

src/assets/properties-panel.css

Makes a CSS selector less specific to make the overrides in bpmn-js-element-templates work:
CSS selector specificity should always work regarless of what stylesheet is loaded first. You can test this by switching the order of stylesheets in the helper in bpmn-js-element-templates:
Related to https://github.com/camunda/camunda-modeler/issues/5059

fix: make CSS selector less specific to allow overriding

---

CHANGELOG.md
src/components/Group.js
test/spec/components/Group.spec.js

Changes the dirty marker text from "Section contains data" to "Section contains edits", to more closely align with the [original intend of the :grey_heart: dot](https://github.com/camunda/camunda-modeler/issues/5126#issuecomment-3102856547):
Steps to try out:
```sh
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#user-data
```
Related to https://github.com/camunda/camunda-modeler/issues/5126

Clarify dirty marker hint
