bpmn-io/properties-panel

- src/bpmn-properties-panel/BpmnPropertiesPanelRenderer.js
- test/spec/bpmn-properties-panel/BpmnPropertiesPanelRenderer.spec.js
This pops up while working with the Camunda Modeler (cf. `PropertiesPanelKeyboardBindings`). 
Related to https://github.com/bpmn-io/properties-panel-next/issues/24#issuecomment-852983455.
> feat: notify on attach + detach

- assets/properties-panel.css
- src/bpmn-properties-panel/provider/zeebe/ZeebePropertiesProvider.js
- src/bpmn-properties-panel/provider/zeebe/properties/MultiInstanceProps.js
- src/bpmn-properties-panel/provider/zeebe/properties/OutputPropagationProps.js
- src/bpmn-properties-panel/provider/zeebe/properties/TargetProps.js
- src/bpmn-properties-panel/provider/zeebe/properties/TaskDefinitionProps.js
- src/bpmn-properties-panel/provider/zeebe/properties/index.js
- src/bpmn-properties-panel/provider/zeebe/utils/CalledElementUtil.js
- src/bpmn-properties-panel/provider/zeebe/utils/ExtensionElementsUtil.js
- src/bpmn-properties-panel/provider/zeebe/utils/HeadersUtil.js
- src/bpmn-properties-panel/provider/zeebe/utils/InputOutputUtil.js
- src/properties-panel/components/entries/ToggleSwitch.js
- test/spec/bpmn-properties-panel/provider/zeebe/MultiInstanceProps.spec.js
- test/spec/bpmn-properties-panel/provider/zeebe/OutputPropagationProps.bpmn
- test/spec/bpmn-properties-panel/provider/zeebe/OutputPropagationProps.spec.js
- test/spec/bpmn-properties-panel/provider/zeebe/TargetProps.bpmn
- test/spec/bpmn-properties-panel/provider/zeebe/TargetProps.spec.js
- test/spec/bpmn-properties-panel/provider/zeebe/TaskDefinitionProps.spec.js
- test/spec/bpmn-properties-panel/provider/zeebe/ZeebePropertiesProvider.spec.js
- test/spec/properties-panel/components/ToggleSwitch.spec.js
> 42 add prop all child variables

- src/bpmn-properties-panel/provider/zeebe/ZeebePropertiesProvider.js
- src/bpmn-properties-panel/provider/zeebe/properties/MessageProps.js
- src/bpmn-properties-panel/provider/zeebe/properties/index.js
- test/spec/bpmn-properties-panel/provider/zeebe/MessageProps.bpmn
- test/spec/bpmn-properties-panel/provider/zeebe/MessageProps.spec.js
Closes #50 
Builds on top of #44
> Implement Message Subscription Correlation Key

- src/bpmn-properties-panel/provider/zeebe/ZeebePropertiesProvider.js
- src/bpmn-properties-panel/provider/zeebe/properties/FormProps.js
- src/bpmn-properties-panel/provider/zeebe/properties/index.js
- src/bpmn-properties-panel/provider/zeebe/utils/IdUtil.js
- test/spec/bpmn-properties-panel/provider/zeebe/Forms.bpmn
- test/spec/bpmn-properties-panel/provider/zeebe/Forms.spec.js
---
Closes https://github.com/bpmn-io/properties-panel-next/issues/49
> Support Form JSON configuration

- package-lock.json
- package.json
- src/bpmn-properties-panel/provider/zeebe/properties/TaskDefinitionProps.js
- src/bpmn-properties-panel/provider/zeebe/utils/HeadersUtil.js
- src/bpmn-properties-panel/provider/zeebe/utils/InputOutputUtil.js
- test/spec/bpmn-properties-panel/provider/zeebe/ZeebePropertiesProvider.bpmn
- test/spec/bpmn-properties-panel/provider/zeebe/ZeebePropertiesProvider.spec.js
* bumps to `zeebe-bpmn-moddlle@0.7.0`
* handles send tasks, script tasks, business rule tasks
Closes #68
> Add Zeebe 1.1 properties support

- src/bpmn-properties-panel/provider/bpmn/properties/ErrorProps.js
- src/bpmn-properties-panel/provider/bpmn/properties/MessageProps.js
- test/spec/bpmn-properties-panel/provider/bpmn/ErrorProps.spec.js
- test/spec/bpmn-properties-panel/provider/bpmn/MessageProps.spec.js
> fix(bpmn): do not blow up on empty error + message names

- src/components/entries/Select.js
- test/spec/components/Select.spec.js
related to bpmn-io/bpmn-properties-panel#4
> feat(select): support disabled option

- src/components/entries/TextField.js
- test/spec/components/TextField.spec.js
related to bpmn-io/bpmn-properties-panel#4
> feat(textField): support disabled option

- .babelrc
- .eslintignore
- .gitignore
- package-lock.json
- package.json
Delivers the source code in a transpiled manner, so we can avoid hacks [like this one](https://github.com/bpmn-io/bpmn-properties-panel/pull/1/files#diff-8e222682e48a1d2eea1bcdc904e33649668fc90a147b39ff5be60cef8371e6b4R55-R64) when consuming.
Closes #80
> chore: deliver transpiled content

- src/components/entries/NumberField.js
- test/spec/components/NumberField.spec.js
Not used by any property so far, but could be important to have it in the future.
> feat(entries): add number field component

- assets/properties-panel.css
Updates the border color for focussed error inputs.
> styles: update error focus border color

- assets/properties-panel.css
- test/spec/components/TextField.spec.js
> 83 improve description styling

- assets/properties-panel.css
- src/components/entries/TextArea.js
- test/spec/components/TextArea.spec.js
Closes #87
_default_
_when defined as monospace (e.g. scripts)_
> feat(text-area): make monospace font optional

- assets/properties-panel.css
- src/components/Group.js
- src/components/ListGroup.js
- src/components/entries/Collapsible.js
Closes https://github.com/bpmn-io/properties-panel/issues/45
> feat: use semantic HTML for buttons

- assets/properties-panel.css
- package-lock.json
- package.json
- src/components/entries/List.js
- src/hooks/index.js
- src/hooks/useKeyFactory.js
- test/spec/components/List.spec.js
- test/spec/components/ListGroup.spec.js
- test/spec/hooks/useKeyFactory.spec.js
> Implement list entry

- assets/properties-panel.css
Little follow-up of #115. 
Let's also use semantic color variables for this.
> style: use semantic variables for disabled input colors

- src/components/entries/Checkbox.js
- src/components/entries/Select.js
- src/components/entries/TextArea.js
- test/spec/components/Checkbox.spec.js
- test/spec/components/Select.spec.js
- test/spec/components/TextArea.spec.js
Related to https://github.com/bpmn-io/bpmn-properties-panel/issues/177
> feat: allow to disable textarea, select, and checkbox

- assets/properties-panel.css
Related to https://github.com/bpmn-io/bpmn-properties-panel/issues/187
> style: add minimal focus outline to checkboxes

- src/PropertiesPanel.js
- test/spec/PropertiesPanel.spec.js
This makes sure we properly update the layout.
> fix(properties-panel): properly update layout

- assets/properties-panel.css
Related to [#505](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/505)
> fix(keyboard navigation): Delete button now shows on tabbing

- assets/properties-panel.css
Related to camunda/camunda-modeler#2664
> style: use consistent add/arrow color also for empty sections

- CHANGELOG.md
> chore(CHANGELOG): update to 0.10.2

- CHANGELOG.md
> chore(CHANGELOG): update to v0.13.0

- src/components/Header.js
> fix(header): set accessible title for documentation ref

- CHANGELOG.md
> chore(CHANGELOG): update to v0.14.0

- src/components/entries/TextArea.js
- src/components/entries/TextField.js
closes #146
test it with 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#input-focus
```
> chore(TextField): use controlled input

- src/components/entries/Checkbox.js
- src/components/entries/NumberField.js
- src/components/entries/Select.js
- src/components/entries/Simple.js
- src/components/entries/ToggleSwitch.js
> Make all input fields controlled

- CHANGELOG.md
Includes:
- https://github.com/bpmn-io/properties-panel/pull/158
> chore(CHANGELOG): update to v0.17.0

- test/spec/components/Checkbox.spec.js
- test/spec/components/Collapsible.spec.js
- test/spec/components/Feel.spec.js
- test/spec/components/Group.spec.js
- test/spec/components/Header.spec.js
- test/spec/components/HeaderButton.spec.js
- test/spec/components/List.spec.js
- test/spec/components/ListGroup.spec.js
- test/spec/components/ListItem.spec.js
- test/spec/components/NumberField.spec.js
- test/spec/components/Select.spec.js
- test/spec/components/Simple.spec.js
- test/spec/components/TextArea.spec.js
- test/spec/components/TextField.spec.js
- test/spec/components/ToggleSwitch.spec.js
> test: increase timeouts for a11y tests

- package-lock.json
- package.json
- src/components/entries/FEEL/Feel.js
- src/components/entries/FEEL/FeelEditor.js
- test/spec/components/Feel.spec.js
Try it out on https://marstamm.github.io/feel-editor-showcase/snapshots/2022-08-09/
or with 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#feel-copy-paste
```
> feat(FEEL): keep FEEL enabled state on copy

- CHANGELOG.md
* `FIX`: ensure focus on `propertiesPanel.showError` ([#182](https://github.com/bpmn-io/properties-panel/pull/182))
> chore(CHANGELOG): update to v0.20.2

- assets/properties-panel.css
Just something I recognized via https://github.com/camunda/camunda-modeler/issues/3126. Since we will use CM6 in multiple places, we should carefully scope styling updates.
> style: scope `.cm-` styles

- CHANGELOG.md
- package-lock.json
- package.json
- rollup.config.js
- test/spec/components/FeelEditor.spec.js
- don't bundle production dependencies
- move diagram-js to dev dependency as it is only used in tests
- update feel-editor to latest version
> chore(dist): don't bundle feel-editor

- CHANGELOG.md
> chore(CHANGELOG): update to v0.24.0

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/entries/FEEL/FeelEditor.js
- test/spec/components/FeelEditor.spec.js
related to https://github.com/camunda/camunda-modeler/issues/3276
> fix(FEEL): buffer `focus` events without offset

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/entries/FEEL/FeelEditor.js
- test/spec/components/Feel.spec.js
> fix: maintain focus when variables change

- CHANGELOG.md
related to https://github.com/bpmn-io/internal-docs/issues/687
> Prepare 1.0.0 release

- src/components/entries/NumberField.js
- test/spec/components/NumberField.spec.js
> feat: enable number field validation and linting errors

- assets/properties-panel.css
Related to https://github.com/camunda/camunda-modeler/issues/3445
> fix: enforce general minimum textarea height

- CHANGELOG.md
> chore(CHANGELOG): update to v1.4.0

- assets/properties-panel.css
- package-lock.json
- package.json
- src/components/entries/FEEL/Feel.js
- src/components/entries/index.js
- src/components/entries/templating/FeelTemplating.js
- src/components/entries/templating/FeelTemplatingEditor.js
- src/components/entries/templating/index.js
- test/TestHelper.js
- test/spec/components/Feel.spec.js
- test/spec/components/FeelEditor.spec.js
- test/spec/components/FeelTemplating.spec.js
- test/spec/components/FeelTemplatingEditor.spec.js
Related to [team-hto/141](https://github.com/camunda/team-hto/issues/141)
> feat: feelers editor

- src/PropertiesPanel.js
- src/hooks/useLayoutState.js
- test/spec/PropertiesPanel.spec.js
- test/spec/components/Collapsible.spec.js
- test/spec/components/Feel.spec.js
- test/spec/components/Group.spec.js
- test/spec/components/ListGroup.spec.js
- test/spec/hooks/useLayoutState.spec.js
Reverts bpmn-io/properties-panel#225
Closes #227
> Revert "feat: use global layout context as single source of truth"

- assets/properties-panel.css
- package-lock.json
- package.json
- src/components/entries/FEEL/Feel.js
- src/components/entries/index.js
- src/components/entries/templating/Templating.js
- src/components/entries/templating/TemplatingEditor.js
- src/components/entries/templating/index.js
- test/spec/components/Feel.spec.js
- test/spec/components/Templating.spec.js
- test/spec/components/TemplatingEditor.spec.js
> feat: support feelers / feel hybrid component

- CHANGELOG.md
- package-lock.json
- package.json
> deps: update to `@bpmn-io/feel-editor@0.7.1`

- CHANGELOG.md
- src/hooks/useStickyIntersectionObserver.js
- test/spec/hooks/useStickyIntersectionObserver.spec.js
> fix(hooks): don't break on missing scrollContainer

- CHANGELOG.md
- assets/properties-panel.css
- src/PropertiesPanel.js
- test/spec/PropertiesPanel.spec.js
related to https://github.com/camunda/camunda-modeler/issues/3602
> chore: remove `open` layout option

- assets/properties-panel.css
Closes #249
form-js demo (grey background): https://demo-update-fx-styles--camunda-form-playground.netlify.app/
camunda-bpmn-js `npm run start:cloud` (white background):
> style: improve fx toggle size and colors

- assets/properties-panel.css
follow-up to https://github.com/bpmn-io/properties-panel/pull/256/files#r1265116807
> chore(CSS): override variables to change dot color

- CHANGELOG.md
> chore(CHANGELOG): update to v3.2.0

- CHANGELOG.md
- src/components/Group.js
- src/components/ListGroup.js
- src/components/entries/Tooltip.js
- test/spec/components/Tooltip.spec.js
> Fix tooltip UI bugs

- src/components/Group.js
- src/components/ListGroup.js
- test/spec/components/Group.spec.js
- test/spec/components/ListGroup.spec.js
> feat(tooltip): remove native tooltip

- CHANGELOG.md
> chore(CHANGELOG): update to v3.3.2

- src/components/Popup.js
- src/components/entries/FEEL/FeelPopup.js
- test/spec/components/FeelPopup.spec.js
- test/spec/components/Popup.spec.js
> fix(feel-popup): do not close popup on escape during auto suggest

- src/components/entries/FEEL/Feel.js
Steps to reproduce: open a popup-editor on an output mapping
> fix(FEEL): remove `undefined` in front of label

- src/components/Popup.js
- test/spec/components/Popup.spec.js
> feat(Popup): allow `PopupContainer` to be a CSS selector

- src/assets/properties-panel.css
related to https://github.com/camunda/camunda-modeler/issues/3876
> fix(FEEL): add popup placeholder error style

- package.json
* introduce `clean` script
* re-use `build` during `build:watch`
> chore: improve build scripts

- src/components/entries/FEEL/Feel.js
- src/components/entries/NumberField.js
- src/components/entries/Select.js
- src/components/entries/TextArea.js
- src/components/entries/TextField.js
- src/components/entries/templating/Templating.js
- test/spec/components/Feel.spec.js
- test/spec/components/NumberField.spec.js
- test/spec/components/Select.spec.js
- test/spec/components/Templating.spec.js
- test/spec/components/TextArea.spec.js
- test/spec/components/TextField.spec.js
related to https://github.com/camunda/camunda-modeler/issues/3070
Root Cause here: https://github.com/camunda/camunda-modeler/issues/3070#issuecomment-1908175398
> fix(Entries): re-validate when validation function changes

- CHANGELOG.md
> chore(CHANGELOG): update to v3.17.0

- package-lock.json
- package.json
- src/components/entries/FEEL/Feel.js
- src/components/entries/FEEL/FeelEditor.js
- test/spec/components/Feel.spec.js
- test/spec/components/FeelEditor.spec.js
Related to https://github.com/camunda/web-modeler/issues/7931
> Provide accessible label to FEEL editor

- src/components/entries/templating/TemplatingEditor.js
> fix: use correct popout icon for templating editor

- src/assets/properties-panel.css
- src/components/Popup.js
- src/components/entries/FEEL/FeelPopup.js
- src/components/icons/Close.svg
- src/components/icons/index.js
- test/spec/components/FeelPopup.spec.js
- test/spec/components/Popup.spec.js
> fix: move popout close button to header

- CHANGELOG.md
- package-lock.json
- package.json
feat: lint first item access
deps: update to @bpmn-io/feel-lint@1.3.0
This adds first-item rule in the FEEL editor.
> feat: lint first item access

- src/components/entries/FEEL/Feel.js
- test/spec/components/Feel.spec.js
Closes #309 
This doesn't work for FEEL editors: 
Follow up to https://github.com/bpmn-io/properties-panel/pull/401
You can test this works via: 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#trim-whitespaces
```
> Trim whitespaces

- CHANGELOG.md
- src/components/entries/FEEL/Feel.js
- src/components/entries/TextArea.js
- src/components/entries/TextField.js
- test/spec/components/Feel.spec.js
- test/spec/components/TextArea.spec.js
- test/spec/components/TextField.spec.js
This reverts commit https://github.com/bpmn-io/properties-panel/commit/bdeebf0f1303004606178f443a778764d7d3d19b. (`git revert bdeebf0f1303004606178f443a778764d7d3d19b`)
> Revert trim whitespace

- CHANGELOG.md
We're going to release https://github.com/bpmn-io/properties-panel/pull/409 as an alpha so it can be integreated into Web Modeler.
I tested this in Desktop and Web Modeler:
> chore(CHANGELOG): update to v3.27-alpha.0

- src/components/entries/FEEL/Feel.js
- src/components/entries/TextArea.js
- src/components/entries/TextField.js
- src/features/debounce-input/debounceInput.js
- test/spec/components/Feel.spec.js
- test/spec/components/TextArea.spec.js
- test/spec/components/TextField.spec.js
Closes #404. #309, 
Related to: https://github.com/camunda/camunda-modeler/issues/2385, https://github.com/camunda/camunda-modeler/issues/4818
- Handling trimming input elements logic across all components (FEEL disabled (Textfield, TextArea), Text Area, Textfields)
- ~~Added test cases for trimming with debounce and without debounced~~ (Nico and I concluded that without debounce doesn't make any sense since it will never serve real world user experience) 
- Added/Adjusted test cases for trimming, debounced input, noop update on blur for all components 
- Unified input handling logic among components 
- Docs added for un documented logic (`debouncedInput`, `handleInputCallback`)
- Adjusted test cases gracefully. earlier no debounced was used violating real world user experience depiction …
> Trimming handles input update and refactoring (code + tests)
